# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin: "dirt" # "air", "contrast", "dark", "dirt", "mint", "sunrise", "default"

# Site Settings
locale: "en"
title: "Hackin' and Tinkerin'"
title_separator: "-"
name: "Mark Cramer"
description: "A collection of blogs related to some of my projects on GitHub"
url: https://mdcramer.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: mdcramer/Deep-Speeling-Blog # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs: false # true, false (default)
words_per_minute: 200
comments:
  provider: disqus # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname: githubmdcramer # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "master"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path: # blank (default) uses feed.xml

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:

# Social Sharing
twitter:
  username: "markdcramer"
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id:

# Site Author
author:
  name: "Mark Cramer"
  avatar: /assets/images/profilepic-small.jpg # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Product Management executive who enjoys hacking around with code in his free time, of which there is never, sadly, enough."
  location: "San Francisco"
  email:
  facebook:
  github: "mdcramer"
  linkedin: "mcramer" # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  stackoverflow: "852795/mark-cramer" # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  twitter: "markdcramer"
  youtube: # "https://youtube.com/c/MichaelRoseDesign"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - LICENSE
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
mathjax: true
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

pagination:
  enabled: true
  debug: false
  per_page: 7
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    permalink: /:coll/
    enabled: true
    slugify:
      mode: raw
      cased: true
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tags/:tag"

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  deep-speeling-blog:
    output: true
    permalink: /deep-speeling-blog/:path/
  perceptron-magic-blog:
    output: true
    permalink: /perceptron-magic-blog/:path/

# Defaults
defaults:
  # All pages with layout of type [single]
  - scope:
      layout: single
    values:
      author_profile: true
      read_time: false
      comments: true # true
      share: true
      related: true

  # _deep-speeling-blog
  - scope:
      path: "_deep-speeling-blog"
      type: deep-speeling-blog
    values:
      layout: single
      permalink: /deep-speeling-blog/:title/

  # _perceptron-magic-blog
  - scope:
      path: "_perceptron-magic-blog"
      type: perceptron-magic-blog
    values:
      layout: single
      permalink: /perceptron-magic-blog/:title/
